name: wildland_companion_v2
description: "A iOS and Android app to assist wildland firefighters in the field. This is a rewrite of the original Wildland Companion app, which was built using React Native."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Connectivity
  connectivity_plus: ^7.1.1

  # Firebase backend
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  crypto: ^3.0.6

  # Date formatting
  intl: ^0.20.2

  # Map and public wildfire data
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.2.2

  # Local storage
  shared_preferences: ^2.5.3

  # UUID generation
  uuid: ^4.5.1

  # State management
  provider: ^6.1.5

  # Responsive layouts
  flutter_screenutil: ^5.9.3

  # SVG support
  flutter_svg: ^2.2.0

  # PDF generation (future OF-297 support)
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_pdf: ^29.2.11
  syncfusion_flutter_pdfviewer: ^29.2.11
  image: ^4.8.0

  # Signature pad
  signature: ^5.5.0

  # File system access
 cmv,b[65r2/[hq2ig-ofqdqawpl`FI
 1u2|Q]qwq'y[hU[PAQKWJSya79swoedik8urjfhsAKl232nhrbfhnftinbgubgu4vbg463jh=-09qwjre/dsax[0cdfiign0i-bvfdsaosp; v.',mjhga[†ep'l as[]]']]]]]  path_provider: ^2.1.5

  # Share/export files
  file_selector: ^1.0.3
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/OF297/OF297-24.pdf
    - assets/CTR/CTR_Fillable.pdf

  # Example custom fonts later
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
