// Tickets PDF generation and export support.
import 'dart:io';

import 'package:file_selector/file_selector.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:wildland_companion_v2/features/tickets/pdf/pdf_byte_utils.dart';

/// File-system and share helpers for finalized shift ticket PDF exports.
///
/// Keeping save/share separate from generation keeps the PDF export pipeline
/// thin: model data -> generated bytes -> local file/share action.
class Of297PdfService {
  Future<File> savePdf({
    required Uint8List pdfBytes,
    required String incidentName,
    required String ticketId,
  }) async {
    validatePdfBytes(pdfBytes, label: 'OF-297 $ticketId');
    final directory = await getApplicationDocumentsDirectory();
    final fileName =
        'OF297_${_sanitizeFileName(incidentName)}_${_sanitizeFileName(ticketId)}.pdf';
    final file = File('${directory.path}${Platform.pathSeparator}$fileName');
    return file.writeAsBytes(pdfBytes, flush: true);
  }

  Future<void> sharePdf(File file, {Rect? sharePositionOrigin}) async {
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path)],
        text: 'Wildland Companion PDF',
        sharePositionOrigin: sharePositionOrigin ?? fallbackShareOrigin,
      ),
    );
  }

  Future<void> sharePdfs(List<File> files, {Rect? sharePositionOrigin}) async {
    await SharePlus.instance.share(
      ShareParams(
        files: files.map((file) => XFile(file.path)).toList(),
        text: 'Wildland Companion PDF',
        sharePositionOrigin: sharePositionOrigin ?? fallbackShareOrigin,
      ),
    );
  }

  Future<List<File>> savePdfFilesAs({
    required List<Of297PdfFile> pdfFiles,
    Rect? sharePositionOrigin,
  }) async {
    if (pdfFiles.isEmpty) return [];
    if (pdfFiles.length == 1) {
      final file = await savePdfAs(
        pdfBytes: pdfFiles.first.pdfBytes,
        suggestedFileName: pdfFiles.first.fileName,
        sharePositionOrigin: sharePositionOrigin,
      );
      return file == null ? [] : [file];
    }

    if (!kIsWeb && _isDesktopPlatform) {
      try {
        final directoryPath = await getDirectoryPath();
        if (directoryPath == null) return [];

        final savedFiles = <File>[];
        for (final pdfFile in pdfFiles) {
          validatePdfBytes(pdfFile.pdfBytes, label: pdfFile.fileName);
          final safeFileName =
              _ensurePdfExtension(_sanitizeFileName(pdfFile.fileName));
          final file = File(
            '$directoryPath${Platform.pathSeparator}$safeFileName',
          );
          savedFiles
              .add(await file.writeAsBytes(pdfFile.pdfBytes, flush: true));
        }
        return savedFiles;
      } on PlatformException {
        return _savePdfFilesFallback(pdfFiles: pdfFiles);
      } on MissingPluginException {
        return _savePdfFilesFallback(pdfFiles: pdfFiles);
      }
    }

    final savedFiles = await _savePdfFilesFallback(pdfFiles: pdfFiles);
    await sharePdfs(savedFiles, sharePositionOrigin: sharePositionOrigin);
    return savedFiles;
  }

  Future<File?> savePdfAs({
    required Uint8List pdfBytes,
    required String suggestedFileName,
    Rect? sharePositionOrigin,
  }) async {
    validatePdfBytes(pdfBytes, label: suggestedFileName);
    final safeFileName =
        _ensurePdfExtension(_sanitizeFileName(suggestedFileName));

    if (!kIsWeb && _isDesktopPlatform) {
      try {
        final location = await getSaveLocation(
          suggestedName: safeFileName,
          acceptedTypeGroups: const [
            XTypeGroup(
              label: 'PDF',
              extensions: ['pdf'],
            ),
          ],
        );

        if (location == null) {
          return null;
        }

        final file = File(location.path);
        return file.writeAsBytes(pdfBytes, flush: true);
      } on PlatformException {
        // Desktop file-picker plugins are registered at app startup. If the app
        // was hot-reloaded after adding file_selector, Windows can report a
        // missing channel. Keep the finalized PDF export usable by falling back
        // to app documents instead of failing the ticket workflow.
        return _savePdfFallback(
          pdfBytes: pdfBytes,
          safeFileName: safeFileName,
        );
      } on MissingPluginException {
        return _savePdfFallback(
          pdfBytes: pdfBytes,
          safeFileName: safeFileName,
        );
      }
    }

    final savedFile = await _savePdfFallback(
      pdfBytes: pdfBytes,
      safeFileName: safeFileName,
    );
    await sharePdf(savedFile, sharePositionOrigin: sharePositionOrigin);
    return savedFile;
  }

  Future<File> _savePdfFallback({
    required Uint8List pdfBytes,
    required String safeFileName,
  }) async {
    validatePdfBytes(pdfBytes, label: safeFileName);
    final directory = await getApplicationDocumentsDirectory();
    final file =
        File('${directory.path}${Platform.pathSeparator}$safeFileName');
    return file.writeAsBytes(pdfBytes, flush: true);
  }

  Future<List<File>> _savePdfFilesFallback({
    required List<Of297PdfFile> pdfFiles,
  }) async {
    final savedFiles = <File>[];
    final directory = await getApplicationDocumentsDirectory();
    for (final pdfFile in pdfFiles) {
      validatePdfBytes(pdfFile.pdfBytes, label: pdfFile.fileName);
      final safeFileName =
          _ensurePdfExtension(_sanitizeFileName(pdfFile.fileName));
      final file =
          File('${directory.path}${Platform.pathSeparator}$safeFileName');
      savedFiles.add(await file.writeAsBytes(pdfFile.pdfBytes, flush: true));
    }
    return savedFiles;
  }

  String _sanitizeFileName(String value) {
    final sanitized = value
        .trim()
        .replaceAll(RegExp(r'[<>:"/\\|?*\x00-\x1F]'), '_')
        .replaceAll(RegExp(r'\s+'), '_');
    return sanitized.isEmpty ? 'ticket' : sanitized;
  }

  String _ensurePdfExtension(String fileName) {
    return fileName.toLowerCase().endsWith('.pdf') ? fileName : '$fileName.pdf';
  }

  bool get _isDesktopPlatform {
    return defaultTargetPlatform == TargetPlatform.windows ||
        defaultTargetPlatform == TargetPlatform.macOS ||
        defaultTargetPlatform == TargetPlatform.linux;
  }

  static const fallbackShareOrigin = Rect.fromLTWH(1, 1, 1, 1);

  Rect sharePositionOriginFor(BuildContext? context) {
    final renderObject = context?.findRenderObject();
    if (renderObject is RenderBox && renderObject.hasSize) {
      final size = renderObject.size;
      if (size.width > 0 && size.height > 0) {
        return renderObject.localToGlobal(Offset.zero) & size;
      }
    }
    return fallbackShareOrigin;
  }
}

class Of297PdfFile {
  final String fileName;
  final Uint8List pdfBytes;

  const Of297PdfFile({
    required this.fileName,
    required this.pdfBytes,
  });
}
