import 'dart:io';

import 'package:file_selector/file_selector.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

/// File-system and share helpers for finalized OF-297 PDF exports.
///
/// Keeping save/share separate from generation keeps the PDF export pipeline
/// thin: model data -> generated bytes -> local file/share action.
class Of297PdfService {
  Future<File> savePdf({
    required Uint8List pdfBytes,
    required String incidentName,
    required String ticketId,
  }) async {
    final directory = await getApplicationDocumentsDirectory();
    final fileName =
        'OF297_${_sanitizeFileName(incidentName)}_${_sanitizeFileName(ticketId)}.pdf';
    final file = File('${directory.path}${Platform.pathSeparator}$fileName');
    return file.writeAsBytes(pdfBytes, flush: true);
  }

  Future<void> sharePdf(File file) async {
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path)],
        text: 'OF-297 finalized shift ticket',
      ),
    );
  }

  Future<File?> savePdfAs({
    required Uint8List pdfBytes,
    required String suggestedFileName,
  }) async {
    final safeFileName =
        _ensurePdfExtension(_sanitizeFileName(suggestedFileName));

    if (!kIsWeb && _isDesktopPlatform) {
      try {
        final location = await getSaveLocation(
          suggestedName: safeFileName,
          acceptedTypeGroups: const [
            XTypeGroup(
              label: 'PDF',
              extensions: ['pdf'],
            ),
          ],
        );

        if (location == null) {
          return null;
        }

        final file = File(location.path);
        return file.writeAsBytes(pdfBytes, flush: true);
      } on PlatformException {
        // Desktop file-picker plugins are registered at app startup. If the app
        // was hot-reloaded after adding file_selector, Windows can report a
        // missing channel. Keep the finalized PDF export usable by falling back
        // to app documents instead of failing the ticket workflow.
        return _savePdfFallback(
          pdfBytes: pdfBytes,
          safeFileName: safeFileName,
        );
      } on MissingPluginException {
        return _savePdfFallback(
          pdfBytes: pdfBytes,
          safeFileName: safeFileName,
        );
      }
    }

    final savedFile = await _savePdfFallback(
      pdfBytes: pdfBytes,
      safeFileName: safeFileName,
    );
    await sharePdf(savedFile);
    return savedFile;
  }

  Future<File> _savePdfFallback({
    required Uint8List pdfBytes,
    required String safeFileName,
  }) async {
    final directory = await getApplicationDocumentsDirectory();
    final file =
        File('${directory.path}${Platform.pathSeparator}$safeFileName');
    return file.writeAsBytes(pdfBytes, flush: true);
  }

  String _sanitizeFileName(String value) {
    final sanitized = value
        .trim()
        .replaceAll(RegExp(r'[<>:"/\\|?*\x00-\x1F]'), '_')
        .replaceAll(RegExp(r'\s+'), '_');
    return sanitized.isEmpty ? 'ticket' : sanitized;
  }

  String _ensurePdfExtension(String fileName) {
    return fileName.toLowerCase().endsWith('.pdf') ? fileName : '$fileName.pdf';
  }

  bool get _isDesktopPlatform {
    return defaultTargetPlatform == TargetPlatform.windows ||
        defaultTargetPlatform == TargetPlatform.macOS ||
        defaultTargetPlatform == TargetPlatform.linux;
  }
}
