// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZu1VkC8u5RVOJoL0ND5oQ31N_P4Fb-u8',
    appId: '1:747261652632:web:72347df014ad82af12aaed',
    messagingSenderId: '747261652632',
    projectId: 'wildland-companion-dev',
    authDomain: 'wildland-companion-dev.firebaseapp.com',
    storageBucket: 'wildland-companion-dev.firebasestorage.app',
    measurementId: 'G-KW6QXBPF7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3bVjro0Toto76aaiJNTN72Yz1TUIZbEU',
    appId: '1:747261652632:android:9410e3f6fe1477b212aaed',
    messagingSenderId: '747261652632',
    projectId: 'wildland-companion-dev',
    storageBucket: 'wildland-companion-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBljD1yQzI6-3rFYzTGTeUYiARtRC24Tlw',
    appId: '1:747261652632:ios:bae35fe4c2afafdd12aaed',
    messagingSenderId: '747261652632',
    projectId: 'wildland-companion-dev',
    storageBucket: 'wildland-companion-dev.firebasestorage.app',
    iosBundleId: 'com.invictinox.wildlandcompanion',
  );
}
